apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipping
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Charts/shipping
    repoURL: https://github.com/stevan95/HelmChartsArgo.git
    targetRevision: master
